version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: linear
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
